### PR TITLE
UICatalog: the stepper controls the number of rows of the table

### PR DESCRIPTION
**Pull request by yostane**
Fixes: #447 
Requires: #452

### CODE REVIEW

**Comment by compnerd** [comment]
Very cool @yostane!

**Comment by compnerd** [comment]
The change looks good to me overall.  What do you think of initializing the stepper to 2 or 3 so that there are elements in the TableView by default?

**Review by compnerd — APPROVED** [review]

**Comment by yostane** [comment]
It's weird, `self.stepper.value = 2.0` does not seem to work. It looks like the `SendMessageW` call does not change the POS.

**Comment by compnerd** [comment]
Ugh, because the parameters are swapped :-(: https://docs.microsoft.com/en-us/windows/win32/controls/udm-setpos32

Is a trivial fix, just swap the two parameters, would you like to put up a PR?

**Comment by yostane** [comment]
Okay I'll do it :). Thanks for the help :)

**Review by compnerd — APPROVED** [review]
Thank you!

**Comment by yostane** [comment]
You're welcome :)

**Pull request merged**
